config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'   
  } 

  devise_scope :user do
    get "user/:id", :to => "users/registrations#detail"
    get "signup", :to => "users/registrations#new"
    get "login", :to => "users/sessions#new"
    get "logout", :to => "users/sessions#destroy"
  end
  
  
  resources :users do
    member do
      get :profile
    end
  end
  get 'users/update'
  patch 'users/update'

  resources :rooms do
    collection do
      get :search
    end
  end


  root to: "start_pages#top"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: %i[show]
  resources :rooms, only: %i[index new create show] do
    resources :reservations, only: %i[index create show], shallow: true
    match '/reservations/new', to: 'reservations#new', via: 'post'
    match '/reservations/new', to: 'reservations#new', via: 'patch'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :rooms, dependent: :destroy
  has_many :reservations, dependent: :destroy

  validates :name, presence: true, length: { maximum: 255 }
  validates :email, uniqueness: true, presence: true
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  protect_from_forgery 
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(current_user.id)
  end


  def profile
    @user = User.find(current_user.id)
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, success: "更新できました"
    else
      flash.now[:danger] = "更新できませんでした"
      render :profile
    end
  end


  private

  def user_params
    params.require(:user).permit(:user_image, :name, :introduction)
  end

  
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/profile.html.erb
<div class="container-fiuld user-new"> 
    <div class="row">
        <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
    <ul>
        <li class="active">
          <%= link_to "アカウント", user_path %>
        </li>
        <li class="">
          <%= link_to "プロフィール", profile_user_path %> 
        </li>
    </ul>
</div>
<div class="col-lg-2 user-nav user-nav-mobile d-lg-none">
    <ul>
        <li class="active">
          <%= link_to "アカウント", user_path %> 
        </li>
        <li class="">
          <%= link_to "プロフィール", profile_user_path %>  
        </li>
    </ul>
</div>
<div class="col-lg-10 user-view">
  <div class="user-view-box">
    <div class="update-content">
        <div class="row">
            <h5>プロフィール</h5>
        </div>
    </div>
      <!-- <form class="edit_user" id="edit_user_81" enctype="multipart/form-data" action="/users/profile" accept-charset="UTF-8" method="post"> -->
    <%= form_with model: @user, local: true do |f| %>
      <input type="hidden" name="_method" value="patch">
      <input type="hidden" name="authenticity_token" value="ItF3/IfCnnMQcedy2nDwBahUyxBnvnD6+c11KBv2HgHUCuiLWzjMPGRB5h0W2uuFVeWYSaOA5VZollnl5BGyWw==">
      <div class="update-content">
          <div class="row">
              <div class="col-md-6 offset-md-3">
                  <div class="icon-box">
                        <% if @user.user_image.present? %>
                          <%= image_tag @user.user_image, class: "icon-image host-icon", alt: "アイコン画像" %>
                        <% else %>
                          <%= image_tag 'default_icon.jpeg' , class: "host-icon" %>
                        <% end %>
                     
                  </div>
              </div>
          </div>
      </div>
      <div class="update-content">
          <div class="row">
              <%= f.label :user_image, "アイコン画像", class: "col-md-3 required-a" %>
              <%= f.file_field :user_image, class: 'mb-4 col-md-9 form-control border-0', accept: 'image/*', placeholder: "アイコン画像をアップロード", id: "user_image"  %>
          </div>
      </div>
      <div class="update-content">
          <div class="row">
              <%= f.label :name, "名前", class: "col-md-3 required-a" %>
              <%= f.text_field :name, class: 'mb-4 col-md-9 form-control', accept: 'image/*', placeholder: "名前を入力", id: "user_name"  %> 
              <!-- <label class="col-md-3 required-a" for="name">名前</label>
              <input class="form-control mb-4 col-md-9" placeholder="名前を入力" type="text" value="nanana" name="user[name]" id="user_name"> -->
          </div>
      </div>
      <div class="update-content">
          <div class="row">
              <%= f.label :introduction, "自己紹介", class: "col-md-3 required-a" %>
              <%= f.text_field :introduction, class: 'mb-4 col-md-9 form-control', placeholder: "自己紹介を入力", id: "user_introduction", rows: 5  %>  
              <!-- <label class="col-md-3 required-a" for="introduction">自己紹介</label>
              <textarea rows="5" class="form-control mb-4 col-md-9" placeholder="自己紹介を入力" name="user[introduction]" id="user_introduction"></textarea> -->
          </div>
      </div>
      <div class="update-content">
        <div class="row">
          <%= f.submit "更新", class: "btn btn-primary col-md-2 mx-3" %>
          <!-- <input type="submit" name="commit" value="更新" class="col-md-2 btn btn-primary mx-3" data-disable-with="更新"> -->
        </div>
      </div>
    <% end %>            
  </div>
</div>

app/views/users/show.html.erb
<div class="container-fiuld user-new"> 
    <div class="row">
        <div class="col-lg-2 user-nav user-nav-pc d-lg-block d-none">
    <ul>
        <li class="active">
          <%= link_to "アカウント", user_path %>
        </li>
        <li class="">
          <%= link_to "プロフィール", profile_user_path %> 
        </li>
    </ul>
</div>
<div class="col-lg-2 user-nav user-nav-mobile d-lg-none">
    <ul>
        <li class="active">
          <%= link_to "アカウント", user_path %>
        </li>
        <li class="">
          <%= link_to "プロフィール", profile_user_path %> 
        </li>
    </ul>
</div>
        <div class="col-md-10 user-view">
            <div class="user-view-box">
                <div class="update-content">
                    <div class="row">
                        <h5>アカウント</h5>
                    </div>
                </div>
                <div class="update-content">
                    <div class="row">
                        <label class="col-md-3" for="email">メールアドレス</label>
                        <div class="col-md-9"><%= @user.email %></div>
                    </div>
                </div>
                <div class="update-content">
                    <div class="row">
                        <label class="col-md-3" for="password">パスワード</label>
                        <div class="col-md-9"><%= @user.encrypted_password %></div>
                    </div>
                </div>
                <div class="update-content">
                    <div class="row">
                        <!--<a class="col-md-2 btn btn-primary mx-3" href="/users/edit">編集</a> -->
                        <%= link_to '編集', edit_user_registration_path, class: "btn btn-primary mx-3" %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>